# Recommended lints for Flutter apps, packages, and plugins.
include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning

linter:
  rules:
    # Recommended rules
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    # Our rules
    - always_declare_return_types
    - always_specify_types
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
